<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.1</version>
    </parent>

    <groupId>de.${app.packageName?lower_case}</groupId>
    <artifactId>${app.baseName}</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <description>App template from test @ spring</description>
    <packaging>pom</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <spring-boot-version>3.3.1</spring-boot-version>
        <openapi-version>2.5.0</openapi-version>
    </properties>

    <modules>
        <module>webclient</module>
        <module>application</module>
        <module>rest</module>
        <module>service</module>
        <module>persistence</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter</artifactId>
                <version>${r"${spring-boot-version}"}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-logging</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-log4j2</artifactId>
                <version>${r"${spring-boot-version}"}</version>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${r"${openapi-version}"}</version>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-common</artifactId>
                <version>${r"${openapi-version}"}</version>
            </dependency>
            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
                <version>42.5.1</version>
                <scope>runtime</scope>
            </dependency>
            <dependency>
                <groupId>${r"${project.groupId}"}</groupId>
                <artifactId>application</artifactId>
                <version>${r"${project.version}"}</version>
            </dependency>
            <dependency>
                <groupId>${r"${project.groupId}"}</groupId>
                <artifactId>rest</artifactId>
                <version>${r"${project.version}"}</version>
            </dependency>
            <dependency>
                <groupId>${r"${project.groupId}"}</groupId>
                <artifactId>service</artifactId>
                <version>${r"${project.version}"}</version>
            </dependency>
            <dependency>
                <groupId>${r"${project.groupId}"}</groupId>
                <artifactId>generator</artifactId>
                <version>${r"${project.version}"}</version>
            </dependency>
            <dependency>
                <groupId>${r"${project.groupId}"}</groupId>
                <artifactId>persistence</artifactId>
                <version>${r"${project.version}"}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
