version: "3.9"
services:
  postgres:
    container_name: reacthookspring-db
    image: postgres:latest
    environment:
      POSTGRES_DB: reacthookspring
      POSTGRES_USER: reacthookspring
      POSTGRES_PASSWORD: reacthookspring
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U reacthookspring'] # <<<---
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - reacthookspring-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - reacthookspring-pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend
    restart: unless-stopped

  reacthookspring-db-keycloak:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: 'keycloak'
      POSTGRES_USER: 'keycloak'
      POSTGRES_PASSWORD: 'keycloak'
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U keycloak'] 
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - reacthookspring-keycloak-db:/var/lib/postgresql/data
    networks:
      - backend

  reacthookspring-keycloak:
    image: jboss/keycloak
    volumes:
      - ./keycloak/imports:/opt/jboss/keycloak/imports
      - ./keycloak/local-test-users.json:/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json
    depends_on:
      reacthookspring-db-keycloak:
        condition: service_healthy
    restart: on-failure
    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm.json
      DB_VENDOR: postgres
      DB_ADDR: reacthookspring-db-keycloak
      DB_PORT: 5432
      DB_USER: 'keycloak'
      DB_PASSWORD: 'keycloak'
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_FRONTEND_URL: 'http://localhost:8080/auth'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '8080:8080'
    networks:
      - backend

networks:
  backend:

volumes:
  reacthookspring-db:
  reacthookspring-pgadmin:
  reacthookspring-keycloak-db:

