version: "3.9"
services:
  db:
    image: mariadb:latest
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'reacthookspring'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'reacthookspring'
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DB_PW_reacthookspring}
      # Password for root access
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: ${DB_PW_PB_ROOT}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 60s
      retries: 30
    expose:
      # Opens port 3306 on the container
      - '3306'
    # Where our data will be persisted
    volumes:
      - /mnt/lj-mariadb/reacthookspring:/var/lib/mysql
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      
  reacthookspring:
    image: starwitorg/reacthookspring:v0.2.13-9
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/reacthookspring?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: reacthookspring
      SPRING_DATASOURCE_PASSWORD: ${DB_PW_reacthookspring}
      KEYCLOAK_AUTH-SERVER-URL: https://pb.starwit.de/auth
      SERVER_USE_FORWARD_HEADERS: "true"
      SERVER_FORWARD_HEADERS_STRATEGY: FRAMEWORK
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

 # Networks to be created to facilitate communication between containers
networks:
  backend:

